#!/usr/bin/env python3
"""
Script to help you get the correct DATABASE_URL for Render.com deployment
"""
import os

def main():
    print("🔧 Jeeva.AI Backend - DATABASE_URL Helper")
    print("=" * 50)
    
    print("\n📋 Step-by-Step Instructions:")
    print("1. Go to https://dashboard.render.com")
    print("2. Click 'New' → 'PostgreSQL'")
    print("3. Fill in:")
    print("   - Name: jeeva-db")
    print("   - Database: jeeva_db")
    print("   - User: jeeva_user")
    print("   - Plan: Free (for testing)")
    print("4. Click 'Create Database'")
    print("5. Copy the DATABASE_URL that Render provides")
    
    print("\n🔍 Your DATABASE_URL should look like:")
    print("postgresql://username:password@hostname:port/database")
    print("\nExample:")
    print("postgresql://jeeva_user:abc123xyz@dpg-xyz123-a.oregon-postgres.render.com:5432/jeeva_db")
    
    print("\n⚠️  Important Notes:")
    print("- Don't use 'localhost' or '127.0.0.1'")
    print("- The hostname will be provided by Render.com")
    print("- Username and password are generated by Render.com")
    print("- Database name should match what you created")
    
    print("\n✅ After getting DATABASE_URL:")
    print("1. Go to your web service settings")
    print("2. Add environment variable:")
    print("   Key: DATABASE_URL")
    print("   Value: [paste the URL from Render.com]")
    
    print("\n🚀 Then your deployment should work!")

if __name__ == "__main__":
    main()
