services:
  - type: web
    name: jeeva-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput
    startCommand: gunicorn jeeva_ai_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 300
    envVars:
      - key: SECRET_KEY
        value: fc+wt)r77c6kkwosf@(%q=zddf@t*bvt(@s6e#_r2rudp4@5f8
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,jeeva-ai-backend-5efz.onrender.com
      - key: GEMINI_API_KEY
        value: AIzaSyB648GVuP7puLLtLNBkxC4AIh0w65v4tg4
      - key: FIRECRAWL_API_KEY
        value: fc-08be9ac92ea34916b337539a1225fb05
    # Note: DATABASE_URL will be provided by the PostgreSQL service

  - type: pserv
    name: jeeva-db
    env: postgresql
    plan: free
    databaseName: jeeva_db
    user: jeeva_user
