services:
  - type: web
    name: jeeva-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        value: fc+wt)r77c6kkwosf@(%q=zddf@t*bvt(@s6e#_r2rudp4@5f8
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: jeeva-ai-backend.onrender.com
    # Note: DATABASE_URL will be provided by the PostgreSQL service

  - type: pserv
    name: jeeva-db
    env: postgresql
    plan: free
    databaseName: jeeva_db
    user: jeeva_user
