# Generated by Django 5.2.7 on 2025-10-10 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('risk_warnings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('analysis_type', models.CharField(default='AI Analysis', max_length=100)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'ai_insights',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('lab_test', 'Lab Test'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('record_date', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'health_records',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
