# Generated by Django 4.2.7 on 2025-10-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
