# Generated by Django 4.2.7 on 2025-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='detailed_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='medicine_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='predictive_insights',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
