# Generated by Django 4.2.7 on 2025-10-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_aianalysis_detailed_report_aianalysis_medicine_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
