# Generated by Django 4.2.7 on 2025-10-25 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_aianalysis_disclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRI_CT_Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=255, unique=True)),
                ('patient_id', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('MRI', 'MRI'), ('CT', 'CT Scan'), ('XRAY', 'X-Ray')], max_length=10)),
                ('summary', models.TextField(help_text='Detailed analysis summary (>100 words)')),
                ('findings', models.JSONField(default=list, help_text='Structured list of detected abnormalities')),
                ('region', models.CharField(help_text='Anatomical region (e.g., brain, chest, abdomen)', max_length=100)),
                ('clinical_significance', models.TextField(help_text='Medical interpretation and potential conditions')),
                ('recommendations', models.JSONField(default=list, help_text='Next-step advice and follow-up recommendations')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20)),
                ('source_model', models.CharField(default='medsiglip-v1', max_length=50)),
                ('doctor_access', models.BooleanField(default=False, help_text='Whether doctors can access this analysis')),
                ('api_usage_tokens', models.IntegerField(default=0, help_text='API tokens used for this analysis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MRI/CT Analysis',
                'verbose_name_plural': 'MRI/CT Analyses',
                'db_table': 'mri_ct_analysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
