# Generated by Django 4.2.7 on 2025-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_mri_ct_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='simplified_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
