# Generated by Django 4.2.7 on 2025-10-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0003_aianalysis_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='ai_disclaimer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
