# Generated by Django 4.2.7 on 2025-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_aianalysis_simplified_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('lab_test', 'Lab Test'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('consent', 'Consent'), ('other', 'Other')], max_length=50),
        ),
    ]
