# Generated by Django 4.2.7 on 2025-10-19 14:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0005_accesslog_aiinsight_consent_consentrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNoteFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('doctor_id', models.UUIDField()),
                ('consultation_id', models.UUIDField(blank=True, null=True)),
                ('file_name', models.TextField()),
                ('file_type', models.TextField(choices=[('image', 'Image'), ('pdf', 'PDF')])),
                ('file_url', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consultation_note_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField()),
                ('doctor_id', models.UUIDField()),
                ('consultation_id', models.UUIDField(blank=True, null=True)),
                ('file_name', models.TextField()),
                ('file_type', models.TextField(choices=[('image', 'Image'), ('pdf', 'PDF')])),
                ('file_url', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescription_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
