# Generated by Django 4.2.7 on 2025-10-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0006_consultationnotefile_prescriptionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='tags',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
