# Generated by Django 4.2.7 on 2025-10-23 07:26

from django.db import migrations
import json


def fix_tags_data(apps, schema_editor):
    """Fix malformed tags data in existing HealthRecord entries using raw SQL"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Fix malformed array literals by setting them to proper JSON arrays
        cursor.execute("""
            UPDATE health_records 
            SET tags = '{}'::text[] 
            WHERE tags::text = '[]' OR tags IS NULL
        """)


def reverse_fix_tags_data(apps, schema_editor):
    """Reverse operation - not needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0007_alter_healthrecord_tags'),
    ]

    operations = [
        migrations.RunPython(fix_tags_data, reverse_fix_tags_data),
    ]
