# Generated by Django 4.2.7 on 2025-10-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0008_auto_20251023_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='tags',
        ),
    ]
