# Generated by Django 4.2.7 on 2025-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0009_auto_20251023_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='key_findings',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='recommendations',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='risk_warnings',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
